### ISSUE TITLE
Use Cron triggers?

### ISSUE THREAD

**Issue by dwertheimer** [DavidWittman/serverless-southwest-check-in#14]
Wondering whether, instead of checking every minute (or 5), the app could just add a Cloudwatch cron trigger for the appropriate time when the checkin times are fetched. Maybe insert two for each (one in case of retry). Not sure if a Lambda function can add its own triggers though...

**Comment by dwertheimer** [comment]
[http://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html](API_PutRule.html)

**Comment by DavidWittman** [comment]
This could definitely work. The creation/cleanup is a little bit involved, and I'd need to make sure the ARN for the check-in function is passed properly, but it's doable. I'll revisit eventually (TM).

**Comment by DavidWittman** [comment]
It looks like AWS Step Functions would be perfect for this. A [Wait state](https://docs.aws.amazon.com/step-functions/latest/dg/awl-ref-states-wait.html) can be defined with a timestamp of when to check in. This would also remove the DynamoDB dependency, since the step functions would control the state.

There's already a [Serverless](https://github.com/horike37/serverless-step-functions) plugin for it too, though it's still in beta.

**Comment by DavidWittman** [comment]
Closed by #17
