### ISSUE TITLE
Retry failed check ins

### ISSUE THREAD

**Issue by DavidWittman** [DavidWittman/serverless-southwest-check-in#4]
It would be helpful to retry failed check ins for the past N minutes, as there can be race conditions i.e. if the Lambda fires at HH:MM:01 and the clock is a little skewed.

**Comment by dwertheimer** [comment]
I changed my code slightly to allow for automatic retries. You may want to use this.

Changed handler.py to:
`    response = dynamo.scan(FilterExpression=Key('check_in').lt(this_minute))`

and had to change serverless permissions to grant that permission:
Effect > Allow: Action:
```
...
        - dynamodb:Scan
```

and change the last line in the handler.py file to send the actual record time instead of the now() time:
`        _delete_check_in(r['check_in'], r['reservation'])
`

This works, but if you encounter the bug where deletes fail (like I did), then it's going to check in every minute forever (which might be bad). So, you should probably (a) figure out where that delete error comes from, and (b) save the retry count and have it stop trying after 5 or so.

**Comment by DavidWittman** [comment]
Fixed by #17
